#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Operator {
    Add,
    Sub,
    Mult,
    MatMult,
    Div,
    FloorDiv,
    Mod,
    Pow,

    LShift,
    RShift,
    BitOr,
    BitXor,
    BitAnd,

    UAdd,
    USub,
    Not,
    Invert,
    And,
    Or,

    Eq,
    NotEq,
    Lt,
    LtE,
    Gt,
    GtE,
    Is,
    IsNot,
    In,
    NotIn,
    AddAssign,
    SubAssign,
    MultAssign,
    MatMultAssign,
    DivAssign,
    FloorDivAssign,
    ModAssign,
    PowAssign,
    LShiftAssign,
    RShiftAssign,
    BitOrAssign,
    BitXorAssign,
    BitAndAssign,
    Walrus,

    Unknown(i32),
}

impl From<i32> for Operator {
    fn from(value: i32) -> Self {
        match value {
            1 => Self::Add,
            2 => Self::Sub,
            3 => Self::Mult,
            4 => Self::MatMult,
            5 => Self::Div,
            6 => Self::FloorDiv,
            7 => Self::Mod,
            8 => Self::Pow,

            9 => Self::LShift,
            10 => Self::RShift,
            11 => Self::BitOr,
            12 => Self::BitXor,
            13 => Self::BitAnd,

            14 => Self::UAdd,
            15 => Self::USub,
            16 => Self::Not,
            17 => Self::Invert,
            18 => Self::And,
            19 => Self::Or,
            20 => Self::Eq,
            21 => Self::NotEq,
            22 => Self::Lt,
            23 => Self::LtE,
            24 => Self::Gt,
            25 => Self::GtE,
            26 => Self::Is,
            27 => Self::IsNot,
            28 => Self::In,
            29 => Self::NotIn,
            30 => Self::AddAssign,
            31 => Self::SubAssign,
            32 => Self::MultAssign,
            33 => Self::MatMultAssign,
            34 => Self::DivAssign,
            35 => Self::FloorDivAssign,
            36 => Self::ModAssign,
            37 => Self::PowAssign,
            38 => Self::LShiftAssign,
            39 => Self::RShiftAssign,
            40 => Self::BitOrAssign,
            41 => Self::BitXorAssign,
            42 => Self::BitAndAssign,
            43 => Self::Walrus,

            other => Self::Unknown(other),
        }
    }
}

impl Operator {
    pub fn as_i32(self) -> i32 {
        match self {
            Self::Add => 1,
            Self::Sub => 2,
            Self::Mult => 3,
            Self::MatMult => 4,
            Self::Div => 5,
            Self::FloorDiv => 6,
            Self::Mod => 7,
            Self::Pow => 8,

            Self::LShift => 9,
            Self::RShift => 10,
            Self::BitOr => 11,
            Self::BitXor => 12,
            Self::BitAnd => 13,

            Self::UAdd => 14,
            Self::USub => 15,
            Self::Not => 16,
            Self::Invert => 17,
            Self::And => 18,
            Self::Or => 19,
            Self::Eq => 20,
            Self::NotEq => 21,
            Self::Lt => 22,
            Self::LtE => 23,
            Self::Gt => 24,
            Self::GtE => 25,
            Self::Is => 26,
            Self::IsNot => 27,
            Self::In => 28,
            Self::NotIn => 29,
            Self::AddAssign => 30,
            Self::SubAssign => 31,
            Self::MultAssign => 32,
            Self::MatMultAssign => 33,
            Self::DivAssign => 34,
            Self::FloorDivAssign => 35,
            Self::ModAssign => 36,
            Self::PowAssign => 37,
            Self::LShiftAssign => 38,
            Self::RShiftAssign => 39,
            Self::BitOrAssign => 40,
            Self::BitXorAssign => 41,
            Self::BitAndAssign => 42,
            Self::Walrus => 43,

            Self::Unknown(value) => value,
        }
    }
}
